[commands.prettier-content]
type = "both"
cmd = [
  "pnpm",
  "exec",
  "prettier",
  "--write"
]
lint-flags = ["--check"]
tidy-flags = ["--write"]
path-args = "absolute-file"
include = ["content/**/**/*.md"]
ok-exit-codes = 0

[commands.prettier-scripts]
type = "both"
cmd = [
  "pnpm",
  "exec",
  "prettier",
  "--write"
]
lint-flags = ["--check"]
tidy-flags = ["--write"]
path-args = "absolute-file"
include = ["assets/js/**"]
ok-exit-codes = 0

[commands.eslint-scripts]
type = "both"
cmd = [
  "pnpm",
  "exec",
  "eslint",
  "."
]
lint-flags = []
tidy-flags = ["--fix"]
path-args = "absolute-file"
include = ["assets/js/**"]
ok-exit-codes = 0

[commands.tsc-scripts]
type = "lint"
cmd = [
  "tsc",
  "--noEmit"
]
include = ["assets/js/**/*.{ts}"]
ok-exit-codes = 0


[commands.stylelint-styles]
type="both"
cmd = [
  "pnpm",
  "exec",
  "stylelint"
]
lint-flags = []
tidy-flags = ["--fix"]
path-args = "absolute-file"
include = ["assets/scss/**"]
ok-exit-codes = 0

[commands.cspell-content]
type="lint"
include = ["*.md"]
cmd = [
  "pnpm",
  "run",
  "lint:cspell",
]
ok-exit-codes = 0

[commands.validate-lockfile]
type = "lint"
cmd = ["mise", "exec", "--", "yq", "eval", "."]
include = ["pnpm-lock.yaml"]
ok-exit-codes = 0
