baseURL = 'https://blog.maxmind.com/'
languageCode = 'en-us'
title = 'MaxMind'
paginate = 6
rssLimit = 6

[outputs]
  home = ['HTML', 'JSON', 'RSS']
  page = ['HTML']

[taxonomies]
  category = 'category'
  tag = 'tag'

[outputFormats.RSS]
  mediatype = 'application/rss'
  baseName = 'feed'

[outputFormats.JSON]
  mediatype = 'application/json'
  baseName = 'featured-posts'

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4
